# -*- coding: utf-8 -*-
"""codesoft3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a22De3Ws8ntGrX4jWOUK4YMyCkqsZZ9E
"""

import random


def computer_choice():
    return random.choice(['rock', 'paper', 'scissors'])
def determine_winner(user, computer):
    if user == computer:
        return "It's a tie!"
    elif (user == 'rock' and computer == 'scissors') or \
         (user == 'scissors' and computer == 'paper') or \
         (user == 'paper' and computer == 'rock'):
        return "You win!"
    else:
        return "You lose!"
def play_round():
    user = input("Choose rock, paper, or scissors: ").lower()
    computer = computer_choice()
    result = determine_winner(user, computer)
    print(f"You chose {user}, computer chose {computer}. {result}")


user_score = 0
computer_score = 0

while True:
    play_round()
    play_again = input("Do you want to play again? (yes/no): ").lower()
    if play_again != 'yes':
        break